[build]
  command = "bun install && bun run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
